import 'package:flutter/material.dart';
import '../services/storage_service.dart';
import 'home_screen.dart';
class TermsAgreementScreen extends StatefulWidget { const TermsAgreementScreen({super.key}); @override State<TermsAgreementScreen> createState() => _TermsAgreementScreenState(); }
class _TermsAgreementScreenState extends State<TermsAgreementScreen> {
  bool _read = false; bool _agree = false;
  @override Widget build(BuildContext context) => WillPopScope(onWillPop: ()=>Future.value(false),
    child: Scaffold(backgroundColor: const Color(0xFF0b1120), body: SafeArea(child: Column(children: [
      Container(padding: const EdgeInsets.all(20), decoration: BoxDecoration(color: Color(0xFF1e293b), borderRadius: BorderRadius.vertical(bottom: Radius.circular(20))), child: Column(children: const [Text('🦅 Raven VPN', style: TextStyle(fontSize:24,fontWeight:FontWeight.bold,color:Color(0xFF10b981))), SizedBox(height:8), Text('Terms & Copyright Agreement', style: TextStyle(color:Color(0xFF94a3b8)))])),
      Container(margin: EdgeInsets.all(16), padding: EdgeInsets.all(12), decoration: BoxDecoration(color: Color(0xFF450a0a), borderRadius: BorderRadius.circular(10), border: Border.all(color: Color(0xFFef4444))), child: Row(children: [Icon(Icons.warning_amber_rounded, color: Colors.red, size:24), SizedBox(width:12), Expanded(child: Text('⚠️ APPEARS ONCE.\nPlease read carefully.', style: TextStyle(color: Colors.white)))])).expand(flex:1, child: SingleChildScrollView(padding: EdgeInsets.all(16), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('1. Acceptable Use', style: TextStyle(fontWeight:FontWeight.bold, fontSize:16)), Text('• Personal, lawful use only.\n• No sharing, reselling, or multi-device.\n• No torrenting, hacking, or illegal content.\n• Violations = instant suspension.'), SizedBox(height:20), Text('2. Copyright', style: TextStyle(fontWeight:FontWeight.bold, fontSize:16)), Text('• All software & configs are protected.\n• Reverse engineering or modification prohibited.\n• Do not distribute copyrighted material.'), SizedBox(height:20), Text('3. Service', style: TextStyle(fontWeight:FontWeight.bold, fontSize:16)), Text('• Provided "as-is". Payments non-refundable after activation.\n• Raven reserves right to suspend for network protection.')]))),
      Container(padding: EdgeInsets.all(16), decoration: BoxDecoration(color: Color(0xFF1e293b), border: Border(top: BorderSide(color: Color(0xFF334155)))), child: Column(children: [
        CheckboxListTile(value: _read, onChanged: (v)=>setState(()=>_read=v!), title: Text('I read & accept Terms & Acceptable Use', style: TextStyle(color: Colors.white, fontSize:13)), dense: true, activeColor: Color(0xFF10b981)),
        CheckboxListTile(value: _agree, onChanged: (v)=>setState(()=>_agree=v!), title: Text('I agree not to modify or redistribute APK', style: TextStyle(color: Colors.white, fontSize:13)), dense: true, activeColor: Color(0xFF10b981)),
        SizedBox(height:12), SizedBox(width: double.infinity, child: ElevatedButton(onPressed: (_read && _agree) ? _accept : null, style: ElevatedButton.styleFrom(backgroundColor: Color(0xFF10b981), disabledBackgroundColor: Color(0xFF334155), padding: EdgeInsets.symmetric(vertical:14), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10))), child: Text('✅ I AGREE', style: TextStyle(fontSize:15, fontWeight: FontWeight.bold))))]))]))));
  Future<void> _accept() async { await StorageService.acceptTerms(); if(!mounted)return; Navigator.pushReplacement(context, MaterialPageRoute(builder: _=>const HomeScreen())); }
}
