 name: raven_vpn
description: Raven Student VPN Client
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  wireguard_flutter: ^0.5.0+1
  flutter_secure_storage: ^9.0.0
  pointycastle: ^3.7.3
  shared_preferences: ^2.2.2
  convert: ^3.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/wg_public_key.raw
